version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  server:
    build: ./server
    ports:
      - "3002:3002"
  rtmpserver:
    build: ./rtmpserver
    ports:
      - "1935:1935"
      - "8000:8000"
