version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  # api:
  #   image: williamyeh/json-server
  #   command: -p 3001 -w db.json --no-cors
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./api:/data
  #   restart: always
  server:
    build: ./server
    ports:
      - "3002:3002"
  rtmpserver:
    build: ./rtmpserver
    ports:
      - "1935:1935"
      - "8000:8000"
