version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  api:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3001 -w db.json
    ports:
      - "3001:3001"
    volumes:
      - ./api:/data
    restart: always
  rtmpserver:
    build: ./rtmpserver
    ports:
      - "1935:1935"
      - "8000:8000"
